config/routes.rb
Rails.application.routes.draw do

  resources :tournaments do
    post 'add_team', on: :member, to: 'tournaments#add_team'
    post 'generate', on: :member, to: 'tournaments#generate'
    resources :matches, only: [:index, :show, :edit, :update] do
      patch 'close', on: :member, to: 'matches#close'
      post 'add_result', on: :member, to: 'results#create'
    end
  end

  resources :teams

  get 'sessions/new'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  root 'bootstrap#index'
  get 'bracket', to:  'bootstrap#bracket'
  get 'panel', to: 'bootstrap#panel'
  get 'panel/edit', to: 'bootstrap#panel_edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_and_belongs_to_many :teams
  has_many :matches, -> { includes :next_match, :home, :away }

  enum status: [ :signup_mode, :active, :finished ]

  validates :name, presence: true, length: { in: 3..64 }
  validates :teams_count,
            inclusion: { in: 2..1024, message: 'is not in range <2; 1024>' },
            power_of_two: true

  def rounds
    Math.log2(teams_count).round
  end

  def generate_bracket
    self.matches.clear # TODO: delete if tested

    shuffle_seeds
    initialize_bracket_generator
    generate_matches

    active!
  end

  def close
    update(status: :finished)
  end

  def winner
    matches.find_by(round_id: rounds - 1).pick_winner
  end

  private
    def shuffle_seeds
      @teams = self.teams.shuffle
    end

    def initialize_bracket_generator
      matches_count = teams_count - 1
      @first_round_matches_count = teams_count / 2
      @rounds = rounds
      @current_round = 0
      @current_match_id = 0

      @matches = []

      matches_count.times { @matches << { } }
      @matches = self.matches.build(@matches)
    end

    def generate_first_round
      full_pairs = teams.length - @first_round_matches_count
      free_pairs = @first_round_matches_count - full_pairs
      team_id = 0

      full_pairs.times do
        @matches[@current_match_id].update_attributes({ round_id: @current_round, home: @teams[team_id],
                          away: @teams[team_id + 1], next_match: @matches[@first_round_matches_count + @current_match_id / 2],
                          next_match_type: @current_match_id % 2, status: 'active'
                        })
        @current_match_id += 1
        team_id += 2
      end


      free_pairs.times do
        @matches[@current_match_id].update_attributes({ round_id: @current_round, home: @teams[team_id], away: nil,
                          home_score: 2, away_score: 0, next_match: @matches[@first_round_matches_count + @current_match_id / 2],
                          next_match_type: @current_match_id % 2
                        })
        @matches[@current_match_id].close
        @current_match_id += 1
        team_id += 1
      end
    end

    def generate_matches
      generate_first_round

      # create matches in others rounds
      @current_round = 1
      next_match_id = @first_round_matches_count * 1.5
      (rounds - 1).downto(1) do |round|
        puts "Round #{round} #{2 ** (round - 1)}"
        matches_in_round = 2 ** (round - 1)
        matches_in_round.times do |m|
          status = @matches[@current_match_id].home.nil? || @matches[@current_match_id].away.nil? ? 'draft' : 'active'

          @matches[@current_match_id].update_attributes({ round_id: @current_round, next_match: @matches[next_match_id],
                                           next_match_type: m % 2, status: status})
          @current_match_id += 1
          if m % 2 == 1
            next_match_id +=1
          end
        end
        @current_round += 1
      end

      @matches.each(&:save)
    end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, except: [:index, :new, :create]
  before_action :require_login, except: [:index, :show]
  before_action :require_tournament_admin, except: [:index, :new, :create, :show, :add_team]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all.includes(:creator)
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = current_user.tournaments.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      update_params = tournament_params
      update_params.except!(:teams_count) unless @tournament.signup_mode?
      if @tournament.update(update_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_team
    if @tournament.signup_mode? && !params[:tournament].nil?
      team = Team.find_by(id: params[:tournament][:team_ids])

      if !@tournament.teams.exists?(team)
        if @tournament.teams.length >= @tournament.teams_count
          flash['danger'] = 'There is no slots left'
        else
          @tournament.teams << team
          flash['notice'] = 'Your team has been singed up to this tournament'
        end
      else
        flash['danger'] = 'Your team is already signed up to this tournament'
      end
    else
      flash['danger'] = 'Registraion for this tournament has been closed'
    end

    redirect_to @tournament
  end

  def generate
    # Check if number of team is valid
    if @tournament.teams.length <= @tournament.teams_count / 2
      flash['danger'] = 'Not enough teams to generate the bracket'
    elsif @tournament.teams.length > @tournament.teams_count
      flash['danger'] = 'Too many teams to generate the bracket'
    else
      @tournament.generate_bracket

      flash[:notice] = 'Bracket has been generated'
    end

    redirect_to @tournament

  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :start_date, :teams_count)
    end


end

app/helpers/tournaments_helper.rb
module TournamentsHelper
  def tournament_admin?
    current_user == @tournament.creator
  end
end

app/views/tournaments/_bracket.html.erb
<div id="tournament">
  <% tournament.rounds.times do |round| %>
    <ul class="round">
      <li class="spacer">&nbsp;</li>

      <% tournament.matches.select { |match| match.round_id == round }.each do |match| %>
          <!-- tournament.matches.select { |match| match.round_id == round }.each -->
          <% if match.free_seed? %>
              <li class="game game-top"><%= match.home.name unless match.home.nil? %> <span>W</span></li>
              <li class="game game-spacer">&nbsp;</li>
              <li class="game game-bottom">Free seed <span>O</span></li>

              <li class="spacer">&nbsp;</li>
          <% else %>
            <li class="game game-top"><%= match.home.name unless match.home.nil? %> <span><%= match.home_score %></span></li>
            <li class="game game-spacer">&nbsp;</li>
            <li class="game game-bottom"><%= match.away.name unless match.away.nil? %> <span><%= match.away_score %></span></li>

            <li class="spacer">&nbsp;</li>
          <% end %>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/tournaments/_form.html.erb
<%= form_for(tournament) do |f| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :teams_count %>
    <% if @tournament.signup_mode? %>
      <%= f.number_field :teams_count, class: 'form-control' %>
    <% else %>
        <%= f.number_field :teams_count, class: 'form-control', disabled: true %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.datetime_select :start_date, class: 'form-control' %>
  </div>

  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<div class="row">
  <h1>Editing Tournament</h1>

  <%= render 'form', tournament: @tournament %>

  <br>
  <%= form_tag generate_tournament_path(@tournament) do %>
      <%= submit_tag 'Generate bracket', class: 'btn btn-success' %>
  <% end %>
  <br>

  <%= link_to 'Show', @tournament, class: 'btn btn-default' %>
  <%= link_to 'Back', tournament_path(@tournament), class: 'btn btn-default' %>
</div>

app/views/tournaments/index.html.erb
<div class="row">
  <%= link_to new_tournament_path do %>
      <button type="button" class="btn btn-primary">Create tournament</button>
  <% end %>
</div>


<div class="row">
  <p id="notice"><%= notice %></p>

  <h1>Tournaments</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Start date</th>
        <th>Creator</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tournaments.each do |tournament| %>
        <tr>
          <td><%= tournament.name %></td>
          <td><%= tournament.start_date %></td>
          <td><%= tournament.creator.name %></td>
          <td><%= tournament.status %></td>
          <td><%= link_to 'Show', tournament %></td>
          <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
          <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tournaments/new.html.erb
<div class="row">
<h1>New Tournament</h1>

<%= render 'form', tournament: @tournament %>

<br>
<%= link_to 'Back', tournaments_path, class: 'btn btn-default' %>
</div>

app/views/tournaments/show.html.erb
<div class="row">
  <%= render 'shared/flash_messages' %>
</div>

<div class="row">
  <div class="col-sm-6">
    <ul class="list-group">
      <li class="list-group-item active">
        <strong>Name:</strong>
        <%= @tournament.name %>
      </li>

      <li class="list-group-item">
        <strong>Start date:</strong>
        <%= @tournament.start_date %>
      </li>

      <li class="list-group-item">
        <strong>Creator:</strong>
        <%= @tournament.creator.name %>
      </li>

      <% if @tournament.finished? %>
          <li class="list-group-item">
            <strong>Winner:</strong>
            <%= @tournament.winner.name %>
          </li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-6">
      <ul class="list-group">
        <li class="list-group-item active"><strong>Teams:</strong> <%= "#{@tournament.teams.count} / #{@tournament.teams_count}" %></li>
      <% @tournament.teams.each do |team| %>
        <li class="list-group-item"><%= team.name %></li>
      <% end %>
      </ul>
  </div>
</div>
<div class="row">
  <% if logged_in? and @tournament.signup_mode? %>
      <h4>Add your team</h4>
    <%= form_tag add_team_tournament_path(@tournament), method: 'post', class: 'form-inline' do %>
        <%= collection_select(:tournament, :team_ids, current_user.teams, :id, :name, {}, { class: 'form-control' }) %>
        <%= submit_tag('Submit', class: 'btn btn-primary') %>
    <% end %>
  <% end %>
</div>
<div class="row">
  <br>
  <% if !@tournament.signup_mode? %>
      <%= render 'bracket', tournament: @tournament %>
  <% end %>

  <% if tournament_admin? %>
      <%= link_to 'Edit', edit_tournament_path(@tournament), class: 'btn btn-default' %>
  <% end %>

  <% if @tournament.active? %>
      <%= link_to 'Matches', tournament_matches_path(@tournament), class: 'btn btn-default' %>
  <% end %>
  <%= link_to 'Back', tournaments_path, class: 'btn btn-default' %>
</div>