config/routes.rb
Rails.application.routes.draw do

  resources :tournaments do
    post 'add_team', on: :member, to: 'tournaments#add_team'
    post 'generate', on: :member, to: 'tournaments#generate'
    resources :matches, only: [:index, :show, :edit, :update] do
      patch 'close', on: :member, to: 'matches#close'
      post 'add_result', on: :member, to: 'results#create'
    end
  end

  resources :teams

  get 'sessions/new'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  root 'bootstrap#index'
  get 'bracket', to:  'bootstrap#bracket'
  get 'panel', to: 'bootstrap#panel'
  get 'panel/edit', to: 'bootstrap#panel_edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :next_match, class_name: 'Match', optional: true
  belongs_to :home, class_name: 'Team', optional: true
  belongs_to :away, class_name: 'Team', optional: true
  belongs_to :tournament

  has_many :results

  enum status: [ :draft, :active, :closed, :conflict]
  enum next_match_type: [ :home, :away ]

  def close
    winner = pick_winner
    if winner
      closed!
      unless next_match.nil?
        next_match[next_match_type + '_id'] = winner.id
        next_match.status = 'active' unless next_match.home.nil? || next_match.away.nil?
        next_match.save
      end
      true
    end
  end

  def pick_winner
    if home_score > away_score
      home
    elsif home_score < away_score
      away
    else
      false
    end
  end

  def free_seed?
    home_score == 2 && away.nil?
  end

  def final?
    next_match.nil?
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_tournament
  before_action :set_match, except: [:index]
  before_action :require_tournament_admin, only: [:edit, :update, :close]

  def index
  end

  def show
  end

  def edit
  end

  def update
    if !@match.active?
      flash[:danger] = 'Match must be active to change the result'
      redirect_to tournament_match_path(@tournament, @match)
    elsif @match.update(match_params)
      flash.now[:notice] = 'Updated match'
      render :edit
    else
      flash.now[:danger] = 'Error'
      render :edit
    end
  end

  def close
    if @match.status != 'active'
      flash[:danger] = 'Match must be active to close'
      redirect_to tournament_match_path(@tournament, @match)
    elsif @match.close
      flash.now[:notice] = 'Match has been closed'
      if @match.final?
        @tournament.close
      end
      render :edit
    else
      flash[:danger] = 'There must be a winner'
      redirect_to edit_tournament_match_path(@tournament, @match)
    end
  end

  private
    def set_tournament
      @tournament = Tournament.find(params[:tournament_id])
    end

    def set_match
      @match = Match.find(params[:id])
    end

    def match_params
      params.require(:match).permit(:home_score, :away_score)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/edit.html.erb
<%= render 'shared/flash_messages' %>

<div class="jumbotron text-center">
  <h1><%= @match.home.name unless @match.home.nil? %> vs <%= @match.away.name unless @match.away.nil? %></h1>
  <p>Status: <%= @match.status %></p>
</div>

<% if @match.active? %>
    <%= form_for [@tournament, @match], html: { class: 'form-inline' } do |f| %>
        <%= f.label :home_score %>
        <%= f.number_field :home_score, class: 'form-control' %>
        <%= f.label :away_score %>
        <%= f.number_field :away_score, class: 'form-control' %>

        <%= f.submit class: 'btn btn-primary' %>
    <% end %>

    <br>
    <%= form_for [@tournament, @match], url: { action: :close } do |f| %>
        <%= f.submit value: 'Close match', class: 'btn btn-danger' %>
    <% end %>
    <br>

    <div class="ul-group">
      <li class="list-group-item active">Results: </li>
      <% @match.results.each do |result| %>
          <li class="list-group-item"><%= "#{result.captain.name} - #{result.home_score}:#{result.away_score}" %></li>
      <% end %>
    </div>
<% end %>

app/views/matches/index.html.erb
<div class="row">
  <% @tournament.rounds.times do |round| %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th colspan="3" class="text-center">Round <%= round + 1%></th>
          </tr>
        </thead>
        <tbody>
        <% @tournament.matches.select { |match| match.round_id == round }.each do |match| %>
            <!-- tournament.matches.where(round_id: round).each -->
          <% if match.free_seed? %>
            <tr>
              <td><%= match.home.name unless match.home.nil? %> vs Free seed (<%= match.status %>)</td>
              <td><%= link_to 'Details', tournament_match_path(@tournament, match) %></td>
              <td><%= link_to 'Edit', edit_tournament_match_path(@tournament, match) if tournament_admin? %></td>
            </tr>
          <% else %>
            <tr>
              <td><%= match.home.name unless match.home.nil? %> vs <%= match.away.name unless match.away.nil? %> (<%= match.status %>)</td>
              <td><%= link_to 'Details', tournament_match_path(@tournament, match) %></td>
              <td><%= link_to 'Edit', edit_tournament_match_path(@tournament, match) if tournament_admin? %></td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
  <% end %>
</div>

app/views/matches/show.html.erb
<%= render 'shared/flash_messages' %>
<div class="row">
  <% if @match.free_seed? %>
    <div class="jumbotron text-center">
      <h1><%= @match.home.name unless @match.home.nil? %> vs Free seed</h1>
      <p>W.O.</p>
    </div>
  <% else %>
    <div class="jumbotron text-center">
      <h1><%= @match.home.name unless @match.home.nil? %> vs <%= @match.away.name unless @match.away.nil? %></h1>
      <p><%= @match.home_score %>:<%= @match.away_score %></p>
    </div>
  <% end %>

  <% if @match.active? %>
    <div>
    <% if (team_captain?(@match.home) || team_captain?(@match.away)) && !result_added? %>
        <h2>Add result</h2>
        <%= form_for [@tournament, @match], as: :result, url: add_result_tournament_match_path,
                     method: :post, html: { class: 'form-inline' } do |f| %>
            <div class="form-group">
              <%= f.label @match.home.name %>
              <%= f.number_field :home_score, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label @match.away.name %>
              <%= f.number_field :away_score, class: 'form-control' %>
            </div>

            <%= f.submit class: 'btn btn-primary' %>
        <% end %>
    <% end %>
    </div>
  <% end %>
</div>